### ISSUE TITLE
Backlog contains messages not all matching the criteria

### ISSUE THREAD

**Issue by percyvega** [alcampos/graylog-plugin-alert-conditional-count#1]
Thanks for the plugin; really useful.

I defined a condition so that it would be matched whenever my application had errors (Severity:ERROR). Everything works well except the stacktrace, because it contains messages that are not errors (some have Severity:ERROR but some have Severity:INFO).

![notallerrors](https://user-images.githubusercontent.com/7452763/36545718-894ec9d2-17b7-11e8-86a7-5e57d95bc0dc.png)

https://github.com/alcampos/graylog-plugin-alert-conditional-count/blob/e23666213ecbcd34b993e5f8a4037b3c77dd201f/src/main/java/com/alexjck/plugins/conditional/alerts/ConditionalCountAlertCondition.java#L168

**Comment by pawankkamboj** [comment]
any update on this issue?

**Comment by alcampos** [comment]
Working on this!

**Comment by alcampos** [comment]
Check now!

**Comment by percyvega** [comment]
Hi Al. Thanks for your message. I tested it and it's still not working. Maybe there is another place (besides the line I pointed out) that also needs the change?

For my specific scenario in production, we are still getting notifications with Severity:INFO in their backlogs even though the alert rule is defined with Severity:ERROR.

**Comment by alcampos** [comment]
Mmmm i can not find this error, cause it works in my enviroment. Will keep checking
